spring:
  application:
    name: communities-service
  mongodb:
    uri: ${MONGODB_URI:mongodb://127.0.0.1:27017/communities?serverSelectionTimeoutMS=2000&connectTimeoutMS=2000}
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      accept-float-as-int: false
    datatype:
      enum:
        fail-on-numbers-for-enums: true
  webflux:
    problemdetails:
      enabled: true

server:
  address: ${SERVER_ADDRESS:127.0.0.1}
  port: ${SERVER_PORT:8080}

paravai:
  demo:
    users: ${DEMO_USERS:alice,bob}
